"""Add game_user Association Table

Revision ID: 255e6c9adebb
Revises: 6d0c2bb457ec
Create Date: 2023-10-01 02:04:45.467042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255e6c9adebb'
down_revision = '6d0c2bb457ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
